AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Metadata:
  Generator: "former2"
Description: ""
Resources:
  LambdaFunction:
    Type: "AWS::Serverless::Function"
    # Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      Description: ""
      FunctionName: "6998_hw3_LF1"
      Handler: "6998_hw3_LF1.lambda_handler"
      CodeUri: "./lambda_functions"
      MemorySize: 128
      Runtime: "python3.8"
      Timeout: 10
      EphemeralStorage: 
        Size: 512
