AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
Description: ""
Transform: 'AWS::Serverless-2016-10-31'
# Parameters:
#   SageMakerEndpointParameter:
#     Type: "String"
Resources:
  LambdaFunction:
    # Type: "AWS::Lambda::Function"
    # DeletionPolicy: "Retain"
    # Properties:
    #   Description: ""
    #   FunctionName: "6998_hw3_LF1"
    #   Handler: "6998_hw3_LF1.lambda_handler"
    #   Architectures: 
    #   - "x86_64"
    #   Code: 
    #     S3Bucket: "prod-iad-c1-djusa-tasks"
    #     S3Key: !Sub "/snapshots/${AWS::AccountId}/6998_hw3_LF1-af72453f-ca92-4a6f-a25e-28324a92d6fe"
    #     S3ObjectVersion: "Rmq1tT388YyEnlLgrCkMuNMiyxmih6jY"
    #   MemorySize: 128
    #   Role: !GetAtt IAMRole.Arn
    #   Runtime: "python3.8"
    #   Timeout: 10
    #   TracingConfig: 
    #     Mode: "PassThrough"
    #   Layers: 
    #   - !Sub "arn:aws:lambda:${AWS::Region}:668099181075:layer:AWSLambda-Python38-SciPy1x:107"
    #   EphemeralStorage: 
    #     Size: 512
    #   Tags: 
    #   - 
    #     Key: "lambda:createdBy"
    #     Value: "SAM"
    Type: "AWS::Serverless::Function"
    DeletionPolicy: "Retain"
    Properties:
      FunctionName: "6998_hw3_LF1"
      Handler: "6998_hw3_LF1.lambda_handler"
      CodeUri: "./lambda_functions"
      MemorySize: 128
      Runtime: "python3.8"
      Timeout: 10
      Layers: 
      - !Sub "arn:aws:lambda:${AWS::Region}:668099181075:layer:AWSLambda-Python38-SciPy1x:107"
      EphemeralStorage: 
        Size: 512

  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      BucketName: "6998-hw3-emails"
      NotificationConfiguration: 
        LambdaConfigurations: 
        - 
          Event: "s3:ObjectCreated:*"
          Function: !GetAtt LambdaFunction.Arn

  # SageMakerEndpoint:
  #   Type: "AWS::SageMaker::Endpoint"
  #   Properties:
  #     EndpointName: !Ref SageMakerEndpointParameter


  IAMRole:
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      RoleName: "w6998-hw3-CFStack-LambdaFunctionRole-1249WZ7W4REX0"
      AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
      - "arn:aws:iam::aws:policy/AmazonSESFullAccess"
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      Description: ""

  IAMRole2:
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/service-role/"
      RoleName: "AmazonSageMaker-ExecutionRole-20221204T134859"
      AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"sagemaker.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
      - !Sub "arn:aws:iam::${AWS::AccountId}:policy/service-role/AmazonSageMaker-ExecutionPolicy-20221204T134859"
      - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
      Description: "SageMaker execution role created from the SageMaker AWS Management Console."